# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to production

on:
  push:
    branches: [ master ]

jobs:
  test_and_build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1

    - name: Yarn install
      run: yarn install

    - name: deploy
      env:
        GH_TOKEN: ${GH_TOKEN}
      run: yarn deploy-storybook
